#name: Manga Hunter CI/CD Pipeline
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  Deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Executing remote ssh commands
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.MANGAHUNTER_ORG_HOST }}
#          username: ${{ secrets.MANGAHUNTER_ORG_USER }}
#          key: ${{ secrets.MANGAHUNTER_ORG_SSH_KEY }}
#          script: |
#            git clone https://github.com/H97-Git/MangaHunter 
#            cd ~/MangaHunter
#            dotnet publish --os linux --arch x65 -p:PublishProfile=DefaultContainer -c Release