name: Manga Hunter CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
#  Build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: 7.0.x
#      - name: Build the solution
#        run: dotnet build -c Release
#  Test:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Test the solution
#      run: dotnet test
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#        
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: 7.0.x
#          
#      - name: Publish the solution
#        run: dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer -c Release
#      
#      - run: docker save manga-hunter-blazor-server:1.0.0 > manga-hunter-blazor-server.tar
#      
#      - name: copy file via ssh password
#        uses: appleboy/scp-action@master
#        with:
#          host: 139.144.73.248
#          username: docker-deploy
#          port: 22
#          key: ${{ secrets.MANGAHUNTER_ORG_SSH_KEY }}
#          source: "manga-hunter-blazor-server.tar"

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MANGAHUNTER_ORG_HOST }}
          username: ${{ secrets.MANGAHUNTER_ORG_USER }}
          key: ${{ secrets.MANGAHUNTER_ORG_SSH_KEY }}
          script: |
            git clone https://github.com/H97-Git/MangaHunter 
            cd ~/MangaHunter
            docker-compose -f Docker/docker-compose-presentation.production.yml down
            dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer -c Release
            docker-compose -f Docker/docker-compose-presentation.production.yml up -d